---
# Locale Naming & Ordering
#
# Locales are sorted lexicographically by locale code.
#
# Naming format:
# - Simple locales:
#   Language native ÔÇô Language English
#
# - Regional / variant locales:
#   Language native (Region native) ÔÇô Language English (Region English)
- locale: ar
  alias: ar
  name: Ïº┘äÏ╣Ï▒Ï¿┘èÏ® - Arabic
  active: true
  dir: rtl
- locale: bg
  alias: ''
  name: ðæÐèð╗ð│ð░ÐÇÐüð║ð© - Bulgarian
  active: true
  dir: ltr
- locale: ca
  alias: ''
  name: Catal├á - Catalan
  active: true
  dir: ltr
- locale: cs
  alias: ''
  name: ─îesky - Czech
  active: true
  dir: ltr
- locale: da
  alias: ''
  name: Dansk - Danish
  active: true
  dir: ltr
- locale: de-de
  alias: de
  name: Deutsch - German
  active: true
  dir: ltr
- locale: el
  alias: ''
  name: ╬ò╬╗╬╗╬À╬¢╬╣╬║╬¼ - Greek
  active: true
  dir: ltr
- locale: en-ca
  alias: ''
  name: English (Canada)
  active: true
  dir: ltr
- locale: en-gb
  alias: ''
  name: English (United Kingdom)
  active: true
  dir: ltr
- locale: en-us
  alias: en
  name: English (United States)
  active: true
  dir: ltr
- locale: es-ca
  alias: ''
  name: Catal├á - Catalan (deprecated, please use Catal├á instead)
  active: true
  dir: ltr
- locale: es-co
  alias: ''
  name: Espa├▒ol (Colombia) - Spanish (Colombia)
  active: true
  dir: ltr
- locale: es-es
  alias: es
  name: Espa├▒ol - Spanish
  active: true
  dir: ltr
- locale: es-mx
  alias: ''
  name: Espa├▒ol (M├®xico) - Spanish (Mexico)
  active: true
  dir: ltr
- locale: et
  alias: ''
  name: Eesti - Estonian
  active: true
  dir: ltr
- locale: fa-ir
  alias: fa
  name: ┘üÏºÏ▒Ï│█î - Persian
  active: true
  dir: rtl
- locale: fi
  alias: ''
  name: Suomi - Finnish
  active: true
  dir: ltr
- locale: fr-ca
  alias: ''
  name: Fran├ºais (Canada) - French (Canada)
  active: true
  dir: ltr
- locale: fr-fr
  alias: fr
  name: Fran├ºais - French
  active: true
  dir: ltr
- locale: he-il
  alias: ''
  name: ÎóÎæÎ¿ÎÖÎ¬ - Hebrew
  active: true
  dir: rtl
- locale: hi-in
  alias: hi
  name: Óñ╣Óñ┐ÓñéÓñªÓÑÇ - Hindi
  active: true
  dir: ltr
- locale: hr
  alias: ''
  name: Hrvatski - Croatian
  active: true
  dir: ltr
- locale: hu
  alias: ''
  name: Magyar - Hungarian
  active: true
  dir: ltr
- locale: id
  alias: ''
  name: Bahasa Indonesia - Indonesian
  active: true
  dir: ltr
- locale: is
  alias: ''
  name: ├ìslenska - Icelandic
  active: true
  dir: ltr
- locale: it-it
  alias: it
  name: Italiano - Italian
  active: true
  dir: ltr
- locale: ja
  alias: ''
  name: µùÑµ£¼Þ¬× - Japanese
  active: true
  dir: ltr
- locale: ko-kr
  alias: ko
  name: Ýò£ÛÁ¡ýû┤ - Korean
  active: true
  dir: ltr
- locale: lt
  alias: ''
  name: Lietuvi┼│ - Lithuanian
  active: true
  dir: ltr
- locale: lv
  alias: ''
  name: Latvie┼íu - Latvian
  active: true
  dir: ltr
- locale: ms-my
  alias: ms
  name: Bahasa Malaysia - Malay
  active: true
  dir: ltr
- locale: nl-nl
  alias: nl
  name: Nederlands - Dutch
  active: true
  dir: ltr
- locale: no-no
  alias: nb
  name: Norsk bokm├Ñl - Norwegian Bokm├Ñl
  active: true
  dir: ltr
- locale: pl
  alias: ''
  name: Polski - Polish
  active: true
  dir: ltr
- locale: pt-br
  alias: ''
  name: Portugu├¬s (Brasil) - Portuguese (Brazil)
  active: true
  dir: ltr
- locale: pt-pt
  alias: pt
  name: Portugu├¬s - Portuguese
  active: true
  dir: ltr
- locale: ro-ro
  alias: ro
  name: Rom├ón─â - Romanian
  active: true
  dir: ltr
- locale: ru
  alias: ''
  name: ðáÐâÐüÐüð║ð©ð╣ - Russian
  active: true
  dir: ltr
- locale: rw
  alias: ''
  name: Ikinyarwanda - Kinyarwanda
  active: true
  dir: ltr
- locale: sk
  alias: ''
  name: Sloven─ìina - Slovak
  active: true
  dir: ltr
- locale: sl
  alias: ''
  name: Sloven┼í─ìina - Slovenian
  active: true
  dir: ltr
- locale: sr-cyrl-rs
  alias: sr
  name: ÐüÐÇð┐Ðüð║ð© (Ðøð©ÐÇð©ð╗ð©Ðåð░) - Serbian (Cyrillic)
  active: true
  dir: ltr
- locale: sr-latn-rs
  alias: ''
  name: srpski (latinica) - Serbian (Latin)
  active: true
  dir: ltr
- locale: sv-se
  alias: sv
  name: Svenska - Swedish
  active: true
  dir: ltr
- locale: th
  alias: ''
  name: Ó©áÓ©▓Ó©®Ó©▓Ó╣äÓ©ùÓ©ó - Thai
  active: true
  dir: ltr
- locale: tr
  alias: ''
  name: T├╝rk├ºe - Turkish
  active: true
  dir: ltr
- locale: uk
  alias: ''
  name: ðúð║ÐÇð░Ðùð¢ÐüÐîð║ð░ - Ukrainian
  active: true
  dir: ltr
- locale: vi
  alias: ''
  name: Tiß║┐ng Viß╗çt - Vietnamese
  active: true
  dir: ltr
- locale: zh-cn
  alias: ''
  name: þ«Çõ¢ôõ©¡µûç - Chinese (Simplified)
  active: true
  dir: ltr
- locale: zh-tw
  alias: ''
  name: þ╣üÚ½öõ©¡µûç - Chinese (Traditional)
  active: true
  dir: ltr
